/**
 * ABO pain-point generation — Furkan's pain-point marketing method.
 *
 * Encodes the same method the Mode-C dress pipeline uses
 * (src/lib/ugc-pipeline/dress-angles.ts), adapted for ABO STATIC ads:
 * for each angle, picture ONE specific sub-buyer, pick the ONE small
 * problem that feels HUGE to them, then earn the claim with a believable
 * MECHANISM grounded in what's VISIBLE in the product photos (never an
 * unverifiable internal feature). Each angle becomes one ad set; you only
 * need one to hit.
 *
 * Differs from dress-angles: static image (not video VO), so each angle
 * also yields a short punchy ON-IMAGE TEXT (the "P4IN"/"FOOTPAIN" trick)
 * and Meta-sized copy. Product photos are fed as vision blocks so the
 * mechanism + image prompt are grounded in the real garment.
 *
 * Uses ANTHROPIC_API_KEY_ADS (isolated ads budget), like translate.ts.
 */

import type Anthropic from "@anthropic-ai/sdk";
import { createAnthropic } from "@/lib/anthropic-factory";
import { trackAnthropicUsage } from "@/lib/usage-tracker";
import { getCurrentBrief, buildAngleBriefPromptBlock } from "@/lib/angle-loop/select";
import { EXPLORATION_FLOOR } from "@/lib/angle-loop/types";

const MODEL = "claude-sonnet-4-6";
// Each attempt is cheap on the happy path (~1.5k output tokens), so 4 is
// insurance against the provider proxy's intermittent mid-output stop
// (documented below on the JSON call) and against short-count under-delivery.
// Bounded by RETRY_BUDGET_MS below so a persistently-truncating model can't
// ride the retry loop past the route's own time budget.
const MAX_ATTEMPTS = 4;
// Ceiling, not a charge — ON THE HAPPY PATH, where billing (and latency) is
// on tokens actually produced. But when stop_reason === "max_tokens" persists
// across retries, the model genuinely produces up to this ceiling on EVERY
// attempt, so BOTH cost and latency scale with the cap — that is precisely
// the failure mode this hardening targets, so it can't be waved away as
// "free". A 3-angle x 3-creative response measures ~1540 output tokens; a
// 5-angle run at the same density is roughly 2500. 4000 keeps comfortable
// headroom for both while capping a single maxed-out attempt at ~96 tok/s
// (measured) to ~42s. The original 2600 was genuinely too tight for a
// 5-angle run; an earlier pass at 8000 overshot it the other way — a single
// maxed-out attempt there costs ~83s, so two of them alone (~166s) exceed
// the route's own `maxDuration = 120` before the vision pass or the route's
// subsequent generateHikePrimaries call even run. See RETRY_BUDGET_MS below,
// which is the actual backstop against that; this cap just keeps any one
// attempt individually affordable.
const JSON_MAX_TOKENS = 4000;
// Wall-clock ceiling on the JSON-generation retry loop below, checked before
// starting attempt 2+ (never before attempt 1) — it can only stop a NEW
// attempt from starting, it can't preempt one already in flight. So the true
// worst case is this budget PLUS one full further attempt, and that sum must
// stay under the route's `maxDuration = 120` alongside what runs after this
// loop returns:
//   RETRY_BUDGET_MS (55s) + one maxed-out attempt (~42s at JSON_MAX_TOKENS=
//   4000, ~96 tok/s) + the route's post-loop generateHikePrimaries call
//   (~14s) ≈ 111s — comfortably inside 120s.
// If either JSON_MAX_TOKENS or this budget changes, redo that arithmetic
// before picking a new value; that's the invariant this constant protects.
// In practice the failures we've actually observed are FAST ones (the model
// stopping early at ~339-416 tokens, ~4s each), so 55s still leaves room for
// several retries in the real-world case — this only trims the slow
// pathological path, which is exactly the one that would otherwise blow the
// route's budget.
const RETRY_BUDGET_MS = 55_000;

// Meta RECOMMENDED (delivery-quality) limits — NOT API hard caps. The
// API accepts longer, but Feed placements truncate past these, so we
// constrain the prompt and defensively clamp the output.
const LIMIT = { primary: 125, headline: 40, description: 30 } as const;

export interface PainPointCopy {
  primaryTexts: string[];
  headlines: string[];
  descriptions: string[];
  /** Hike-style archetype primaries (exactly 3) applied to EVERY ad of the
   *  ad set as Meta multiple-text options. Generated by
   *  hike-copy/generate.ts at preview time; legacy runs lack it. */
  primaryOptions?: string[];
  /** Hike-style register headlines (exactly 3), index-paired to
   *  primaryOptions. Same lifecycle: preview-generated, legacy runs lack it. */
  headlineOptions?: string[];
}

export interface PainPoint {
  slug: string;
  label: string;
  /** The SPECIFIC sub-buyer this angle pictures (Furkan's "close your eyes
   *  and see her"). Preview-only; not sent to Meta. Optional so the launch
   *  path + minimal test fixtures don't need to supply it. */
  buyer?: string;
  /** The ONE small problem that feels HUGE to that buyer. */
  painPoint?: string;
  /** The visible, believable reason the product fixes it — grounded in the
   *  product photo, never an unverifiable internal feature. */
  mechanism?: string;
  /** Short, punchy on-image text (3-8 chars, e.g. "P4IN"). Rendered onto
   *  the AtlasCloud creative. */
  onImageText?: string;
  /** AtlasCloud image prompt (square, no faces, white bg, on-image text). */
  imagePrompt: string;
  /** Collection runs only: 0-based index into the product set (matches
   *  scrapedProducts order) of the garment that best expresses this angle.
   *  Absent on single-product runs or when the model's pick was invalid. */
  productIndex?: number;
  productTitle?: string;
  /** That product's reference photo — grounds this angle's ad-set creatives. */
  productImageUrl?: string;
  copy: PainPointCopy;
}

/** One product in the pain-point grounding set (1 = single-product run,
 *  2-4 = collection run's top best-sellers, scrape order). */
export interface AboProductInput {
  title: string;
  description?: string;
  /** Public https photo URLs of THIS product; [0] is the creative reference. */
  imageUrls: string[];
}

export interface GeneratePainPointsArgs {
  /** Legacy single-product input. Ignored when `products` is present. */
  product?: { title: string; description?: string };
  /** Collection-aware input: 1-4 products (top best-sellers, scrape order).
   *  When >1, angles are collection-level and each is tagged with the
   *  product that best expresses it. */
  products?: AboProductInput[];
  collection?: string;
  /** Public product photo URLs — fed to Claude vision so the mechanism +
   *  image prompt are grounded in the real product (Furkan's "believable
   *  reason you can SEE"). Optional; falls back to text-only. Ignored when
   *  `products` is present (each product carries its own imageUrls). */
  productImageUrls?: string[];
  /** Brand name — referenced at most once; premium brands are NEVER named
   *  ("like a luxury brand, without saying which"). */
  brandName?: string;
  /** Number of pain points / ad sets to generate (caller already clamped 1-5). */
  count: number;
  /** Number of single ads per ad set — sizes each copy array (2-3). */
  creativesPerPainPoint: number;
  /** Meta ad-account id — scopes the Angle Brief lookup. Optional; falls
   *  back to META_AD_ACCOUNT_ID inside getCurrentBrief. */
  accountId?: string;
}

function normalizeProducts(args: GeneratePainPointsArgs): AboProductInput[] {
  if (args.products && args.products.length > 0) {
    return args.products
      .filter((p) => typeof p.title === "string" && p.title.trim().length > 0)
      .slice(0, 4)
      .map((p) => ({
        title: p.title.trim(),
        description: p.description,
        imageUrls: (p.imageUrls ?? []).filter((u) => /^https:\/\//i.test(u)).slice(0, 4),
      }));
  }
  if (!args.product?.title) {
    throw new Error("pain-points: either `products` or `product` is required");
  }
  return [
    {
      title: args.product.title,
      description: args.product.description,
      imageUrls: (args.productImageUrls ?? []).filter((u) => /^https:\/\//i.test(u)).slice(0, 4),
    },
  ];
}

export function slugify(label: string): string {
  return (
    label
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "pain"
  );
}

/** Truncate at a word boundary when over `max`, logging the cut. */
export function clampCopyField(text: string, max: number, field: string): string {
  const t = (text ?? "").trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const atBoundary = cut.replace(/\s+\S*$/, "").trim() || cut.trim();
  console.warn(
    `[abo:pain-points] ${field} over ${max} chars, truncated: "${t.slice(0, 60)}…"`,
  );
  return atBoundary;
}

/** Coerce a model copy array to exactly `n` entries, padding from the
 *  first entry (or `fallback`) and clamping each to `max`. */
function sizeAndClamp(
  arr: unknown,
  n: number,
  max: number,
  field: string,
  fallback: string,
): string[] {
  const list = Array.isArray(arr)
    ? arr.filter((s): s is string => typeof s === "string" && s.trim().length > 0)
    : [];
  const out: string[] = [];
  for (let i = 0; i < n; i++) {
    out.push(clampCopyField(list[i] ?? list[0] ?? fallback, max, field));
  }
  return out;
}

function buildSystemPrompt(
  args: GeneratePainPointsArgs,
  briefBlock: string,
  products: AboProductInput[],
): string {
  const n = args.count;
  const c = args.creativesPerPainPoint;
  return [
    "You are a direct-response performance marketer trained in PAIN-POINT marketing. Your craft: a general store, but every ad targets ONE specific small problem that feels HUGE to one specific sub-person — and only ONE pain point per ad set, because you only need one to hit.",
    "",
    "METHOD (follow it literally, per angle):",
    "- CLOSE YOUR EYES and picture the EXACT buyer for THIS product — a real, specific person: their body/situation, the moment they feel the problem, the insecurity or frustration. Not 'a shopper' — a SPECIFIC them, inferred from what this product is and who it's for.",
    "- Pick ONE pain point that feels HUGE to THAT person (small, concrete, emotional — e.g. shoes → 'pain in my ankle by midday' / 'my size is never in stock'; dress → 'the button strains over my belly' / 'I sweat and it shows'; the kind of tiny problem they'd never say out loud but feel every time).",
    "- USE THE VISIBLE-FEATURE NOTES + product description below (they capture what is visible in the product photos). Name ONE concrete, VISIBLE reason the fix is believable — a cut, material, sole, fit, strap, drape, thickness or finish named in the notes/description. This is the MECHANISM that earns the claim from a buyer who's scrolled past a thousand ads and believes none of them. NEVER claim internal or unverifiable features not in the notes/description (no 'orthopedic insole', 'memory foam', 'shaping panel', 'compression').",
    "- Benefit language is SENSORY and concrete — how it feels/looks for them ('you won't sweat', 'walk like you're on clouds', 'no ache by the end of the day'), never vague hype ('premium', 'trendy', 'must-have'). You may evoke a luxury feel WITHOUT naming any brand (never write a premium brand name).",
    "- The ON-IMAGE TEXT is a pattern-interrupt: a very short, punchy word/phrase (3-8 chars) that makes the scroller stop — spell it to grab the eye if it helps (e.g. 'P4IN', 'FOOTPAIN', 'TOO HOT'). It conveys the pain, not the product name. It MUST be a real English word/phrase — never another language (no German, French, etc.).",
    "- LANGUAGE: every text field you output — label, buyer, painPoint, mechanism, onImageText, and all copy — MUST be written in natural US English. This is non-negotiable, even when a foreign word would be shorter or punchier for the on-image text.",
    ...(products.length > 1
      ? [
          "",
          `COLLECTION MODE: you are writing angles for a COLLECTION of ${products.length} related products (listed in the user message as Product 1-${products.length}), sending traffic to the collection page. Each angle targets a sub-buyer of the collection's CATEGORY. For each angle, pick the ONE product (by number) whose VISIBLE features best express that angle — its photo becomes the ad image, so the mechanism and imagePrompt MUST be grounded in THAT product's visible-feature notes, and different angles should pick different products when the fit is equally strong.`,
        ]
      : []),
    ...(briefBlock ? ["", briefBlock] : []),
    "",
    `Produce ${n} DISTINCT angles — each a DIFFERENT sub-buyer AND a DIFFERENT pain point (never repeat). Each becomes one ad set in an ABO test.`,
    "",
    `Output ONE JSON object (no preamble, no markdown fences): {"painPoints":[ ... ]} with exactly ${n} objects, each:`,
    "{",
    `  "label": "<3-6 word name for the angle>",`,
    ...(products.length > 1
      ? [`  "product": <1-based number of the ONE product that best expresses this angle>,`]
      : []),
    `  "buyer": "<one sentence picturing the SPECIFIC sub-buyer: who they are, body/situation, the moment they feel it>",`,
    `  "painPoint": "<the ONE small problem that feels huge to them, plainly stated>",`,
    `  "mechanism": "<the ONE visible reason the product fixes it, grounded in the photo — one short clause, ~8-18 words, no unverifiable internal features>",`,
    `  "onImageText": "<3-8 char punchy on-image text conveying the pain, in ENGLISH (e.g. 'P4IN')>",`,
    `  "imagePrompt": "<prompt to generate ONE static ad image: a SQUARE 1:1, PHOTOREALISTIC product photo of THIS product as the CLEAR HERO on a clean white background (studio photoshoot style) that does NOT look AI-generated. PRODUCT ONLY — no human faces, hands, limbs, bodies or mannequins. Render the English onImageText VERBATIM but SMALL and legible in ONE corner (occupying at most ~15% of the image), as clean bold letters with a thin outline or soft drop-shadow for contrast — NEVER a solid colored bar, banner or black band, and it must NOT cover, cross or obscure the product. Describe the product faithfully from the visible-feature notes + description.>",`,
    `  "copy": {`,
    `    "primaryTexts": [${c} strings <= ${LIMIT.primary} chars — open by naming the FEELING/pain (the hook), then the sensory fix + the visible mechanism],`,
    `    "headlines": [${c} strings <= ${LIMIT.headline} chars, front-load the hook],`,
    `    "descriptions": [${c} strings <= ${LIMIT.description} chars]`,
    `  }`,
    "}",
    "",
    "RULES: ALL output text (label, buyer, painPoint, mechanism, onImageText, copy) MUST be in US English — never another language; one pain point + one buyer per angle, all distinct; sensory/benefit language, never hype; never name a premium brand; ground the mechanism in what's visible. IMAGE RULES: product is the clear hero on clean white, photoreal (not AI-looking), PRODUCT ONLY (no faces, hands, limbs, bodies, mannequins); on-image text 3-8 chars, rendered SMALL in ONE corner (≤~15% of the image), clean letters with a thin outline/soft shadow, NEVER a solid bar/band, NEVER covering the product. Output the JSON object only.",
  ].join("\n");
}

function buildUserPrompt(
  args: GeneratePainPointsArgs,
  visualDescription: string,
  products: AboProductInput[],
): string {
  const blocks: string[] = [];
  if (args.brandName?.trim()) {
    blocks.push(`Brand: ${args.brandName.trim()} (reference at most once; NEVER name a premium/luxury brand).`);
  }
  if (products.length > 1) {
    for (let i = 0; i < products.length; i++) {
      blocks.push(`Product ${i + 1}: ${products[i].title}`);
      if (products[i].description?.trim()) {
        blocks.push("Description:", products[i].description!.trim().slice(0, 600));
      }
    }
  } else {
    blocks.push(`Product title: ${products[0].title}`);
    if (products[0].description?.trim()) {
      blocks.push("Description:", products[0].description!.trim().slice(0, 1500));
    }
  }
  if (args.collection?.trim()) blocks.push(`Collection: ${args.collection.trim()}`);
  if (visualDescription.trim()) {
    blocks.push(
      "",
      "VISIBLE-FEATURE NOTES (from the product photos — ground the mechanism and imagePrompt in these):",
      visualDescription.trim(),
    );
  }
  blocks.push("", "Output the JSON now.");
  return blocks.join("\n");
}

/**
 * Plain-vision pass: describe ONLY what is visibly true in the product photos.
 *
 * qcode reliably handles image + NO tools/JSON/prefill (plain vision), but
 * intermittently mangles image + JSON-in-prompt (empty body / preamble). So we
 * split: this call derives prose "visible-feature notes", and the pain-point
 * JSON is generated separately, TEXT-ONLY, grounded on those notes. Returns ""
 * on any failure so generation falls back to title/description grounding — a
 * weaker mechanism, but never a hard failure. See
 * reference_qcode-drops-tools-on-images.
 */
async function describeProductsVisually(
  anthropic: ReturnType<typeof createAnthropic>,
  products: AboProductInput[],
  collection: string | undefined,
): Promise<string> {
  const multi = products.length > 1;
  // Single product: up to 4 photos of that one garment (today's behavior).
  // Collection: ONE photo per product, labeled, so "image j" maps to
  // "Product n" unambiguously even when a product has no photo.
  const pairs = multi
    ? products
        .map((p, i) => ({ n: i + 1, title: p.title, url: p.imageUrls[0] }))
        .filter((x): x is { n: number; title: string; url: string } => !!x.url)
    : products[0].imageUrls.slice(0, 4).map((url) => ({ n: 1, title: products[0].title, url }));
  if (pairs.length === 0) return "";
  const imageBlocks = pairs.map((x) => ({
    type: "image" as const,
    source: { type: "url" as const, url: x.url },
  }));
  const prompt = multi
    ? [
        `These are product photos from the "${collection ?? "collection"}" collection: ` +
          pairs.map((x, j) => `image ${j + 1} = Product ${x.n} ("${x.title}")`).join(", ") +
          ".",
        'For EACH product, in 1-3 sentences describe ONLY what is visibly true about it — cut, material, sole, strap, neckline, drape, fit, thickness, finish, colour. Concrete features a shopper could verify from the photo. No marketing language, no invented internal features. Start each product\'s notes with "Product <n> (<title>):" on its own line. If a photo is unclear, say what you can and stop.',
      ].join("\n")
    : [
        `Look at these product photos of "${products[0].title}".`,
        "In 2-4 sentences, describe ONLY what is visibly true about the product — cut, material, sole, strap, neckline, drape, fit, thickness, finish, colour. Concrete features a shopper could verify from the photo. No marketing language, no invented internal features. If the photos are unclear, say what you can and stop.",
      ].join("\n");
  try {
    const res = await anthropic.messages.create({
      model: MODEL,
      max_tokens: multi ? 700 : 400,
      messages: [{ role: "user", content: [...imageBlocks, { type: "text" as const, text: prompt }] }],
    });
    await trackAnthropicUsage({ usage: res.usage, model: MODEL, purpose: "abo-pain-points-vision" });
    return res.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("")
      .trim();
  } catch (e) {
    console.warn(
      "[abo:pain-points] vision describe failed, falling back to text-only grounding:",
      e instanceof Error ? e.message : e,
    );
    return "";
  }
}

export async function generatePainPoints(
  args: GeneratePainPointsArgs,
): Promise<PainPoint[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY_ADS || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY_ADS not set");
  const anthropic = createAnthropic({ apiKey, purpose: "abo-pain-points", ads: true });

  // Angle Loop: steer angles with the store's brief when one exists.
  // Fail-open — any error here yields the exact legacy prompt.
  let briefBlock = "";
  try {
    const brief = await getCurrentBrief(args.accountId);
    if (brief && (brief.weights.length > 0 || brief.avoid.length > 0)) {
      const explorationSlots = Math.max(1, Math.round(args.count * EXPLORATION_FLOOR));
      briefBlock = buildAngleBriefPromptBlock(brief, explorationSlots);
    }
  } catch (e) {
    console.warn("[angle-loop] brief injection skipped:", e instanceof Error ? e.message : e);
  }
  // Ground the pain points in the real product WITHOUT sending an image on the
  // JSON call: qcode intermittently mangles an image+JSON request (empty body /
  // preamble — observed live in ABO composed + overlay). So do a PLAIN-VISION
  // describe pass first (qcode's one reliable image mode), then generate the
  // JSON text-only from those notes. See reference_qcode-drops-tools-on-images.
  const products = normalizeProducts(args);
  const visualDescription = await describeProductsVisually(anthropic, products, args.collection);

  const system = buildSystemPrompt(args, briefBlock, products);
  const userText = buildUserPrompt(args, visualDescription, products);
  // TEXT-ONLY messages — no image block. The image+JSON combo is exactly what
  // qcode mangles; the visible-feature notes above carry the grounding instead.
  const messages: Anthropic.MessageParam[] = [{ role: "user", content: userText }];

  const loopStart = Date.now();
  let lastErr: unknown = null;
  let lastRaw = "";
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    // Checked before starting attempt 2+ only — attempt 1 always runs
    // regardless of how long the (already-completed) brief lookup + vision
    // pass took, since `loopStart` is taken right here, not at function entry.
    if (attempt > 1) {
      const elapsedMs = Date.now() - loopStart;
      if (elapsedMs > RETRY_BUDGET_MS) {
        throw new Error(
          `pain-points: giving up after ${attempt - 1} attempts / ${Math.round(elapsedMs / 1000)}s ` +
            `(last: ${lastErr instanceof Error ? lastErr.message : lastErr}). Stopping before the retry ` +
            `loop itself blows the route's own time budget.`,
        );
      }
    }
    // The SDK call sits INSIDE the try: a transient network error, a rate
    // limit, or the upstream returning a malformed/empty response at the
    // HTTP layer must be retried exactly like a validation failure — that is
    // the actual failure the operator hit in production (a bare 502 with no
    // trace), and it used to bypass every attempt + all of the diagnostics
    // below by throwing before parsePainPoints ever ran.
    let raw = "";
    let stopReason: string | null = null;
    try {
      const res = await anthropic.messages.create({
        model: MODEL,
        max_tokens: JSON_MAX_TOKENS,
        system,
        messages,
      });
      await trackAnthropicUsage({ usage: res.usage, model: MODEL, purpose: "abo-pain-points" });
      raw = res.content.filter((b): b is Anthropic.TextBlock => b.type === "text").map((b) => b.text).join("").trim();
      lastRaw = raw;
      // Known upstream flake: the provider proxy in front of Anthropic
      // intermittently stops mid-output. stop_reason lets us tell that apart
      // from a genuine prompt/formatting bug instead of just reporting "N
      // chars of valid-looking JSON" and leaving it to guesswork.
      stopReason = res.stop_reason ?? null;
      return parsePainPoints(raw, args, products, stopReason);
    } catch (err) {
      lastErr = err;
      console.warn(
        `[abo:pain-points] attempt ${attempt}/${MAX_ATTEMPTS} failed (stop_reason=${stopReason ?? "unknown"}, raw length=${raw.length}):`,
        err instanceof Error ? err.message : err,
      );
      if (attempt === MAX_ATTEMPTS) break;
      // Only replay the previous turn when there IS a previous turn to
      // replay. An SDK-level throw (network error, rate limit, malformed
      // upstream response) never produced any assistant output, so `raw` is
      // still "" here — pushing an empty assistant message would poison the
      // conversation history for no reason; just retry the same request.
      if (raw) {
        messages.push({ role: "assistant", content: raw });
        messages.push({
          role: "user",
          content: `Your output failed validation: ${err instanceof Error ? err.message : String(err)}\n\nRe-emit the COMPLETE JSON object only — no preamble, no fences.`,
        });
      }
    }
  }
  throw new Error(
    `pain-points: generation failed after ${MAX_ATTEMPTS} attempts. Last: ${lastErr instanceof Error ? lastErr.message : lastErr}. Raw(120): ${lastRaw.slice(0, 120)}`,
  );
}

function parsePainPoints(
  raw: string,
  args: GeneratePainPointsArgs,
  products: AboProductInput[],
  stopReason?: string | null,
): PainPoint[] {
  const json = raw
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();
  let parsed: { painPoints?: unknown };
  try {
    parsed = JSON.parse(json);
  } catch {
    // Twice on prod the model stopped mid-output (the provider proxy in
    // front of Anthropic is known to do this intermittently) and the error
    // read like a prompt bug because it showed only a clean-looking 120-char
    // excerpt. Naming stop_reason + the full raw length turns "non-JSON: {"
    // into an actionable "was this truncated, or genuinely malformed?".
    const truncationNote =
      stopReason === "max_tokens"
        ? " — response was TRUNCATED by the token limit (stop_reason=max_tokens)"
        : ` (stop_reason=${stopReason ?? "unknown"})`;
    throw new Error(
      `model returned non-JSON${truncationNote}, raw length ${raw.length}: ${raw.slice(0, 120)}`,
    );
  }
  const list = Array.isArray(parsed.painPoints) ? parsed.painPoints : [];
  // A short list is silently accepted downstream via slice(0, count) unless
  // we reject it here — and the count is the number of ad sets in the ABO
  // test, so under-delivering silently changes the operator's budget split.
  // Zero falls out of this same check (0 < count whenever count >= 1).
  if (list.length < args.count) {
    throw new Error(
      `model returned ${list.length} pain points, expected exactly ${args.count}`,
    );
  }

  const seen = new Set<string>();
  return list.slice(0, args.count).map((p: Record<string, any>, i: number) => {
    const label =
      typeof p?.label === "string" && p.label.trim() ? p.label.trim() : `Angle ${i + 1}`;
    let slug = slugify(label);
    while (seen.has(slug)) slug = `${slug}-${i}`;
    seen.add(slug);

    const buyer = typeof p?.buyer === "string" ? p.buyer.trim() : "";
    const painPoint = typeof p?.painPoint === "string" ? p.painPoint.trim() : label;
    const mechanism = typeof p?.mechanism === "string" ? p.mechanism.trim() : "";
    const onImageText = (typeof p?.onImageText === "string" && p.onImageText.trim()
      ? p.onImageText.trim()
      : label
    ).slice(0, 16);

    // Collection runs: the model picks the ONE product (1-based) that best
    // expresses this angle; store 0-based to match scrapedProducts order.
    // Out-of-range / missing picks and single-product runs stay untagged.
    const rawIdx = Number((p as Record<string, unknown>)?.product);
    const tagged =
      products.length > 1 && Number.isInteger(rawIdx) && rawIdx >= 1 && rawIdx <= products.length
        ? products[rawIdx - 1]
        : null;

    const promptHint =
      typeof p?.imagePrompt === "string" && p.imagePrompt.trim()
        ? p.imagePrompt.trim()
        : `Photorealistic product shot of ${(tagged ?? products[0]).title}, clean white background, no human faces, bold on-image text "${onImageText}".`;
    const imagePrompt = /square|1:1/i.test(promptHint)
      ? promptHint
      : `${promptHint} Square 1:1 composition.`;

    return {
      slug,
      label,
      buyer,
      painPoint,
      mechanism,
      onImageText,
      imagePrompt,
      ...(tagged
        ? {
            productIndex: rawIdx - 1,
            productTitle: tagged.title,
            productImageUrl: tagged.imageUrls[0],
          }
        : {}),
      copy: {
        primaryTexts: sizeAndClamp(p?.copy?.primaryTexts, args.creativesPerPainPoint, LIMIT.primary, "primary", painPoint || label),
        headlines: sizeAndClamp(p?.copy?.headlines, args.creativesPerPainPoint, LIMIT.headline, "headline", label),
        descriptions: sizeAndClamp(p?.copy?.descriptions, args.creativesPerPainPoint, LIMIT.description, "description", "Shop now"),
      },
    };
  });
}

// Composed-mode (Option 2) creative-spec generation. Additive — the overlay
// path above (generatePainPoints) is untouched. Re-exported here so the
// composed path is reachable through the pain-points module surface.
export {
  generateCreativeSpecs,
  type GenerateCreativeSpecsArgs,
} from "./composed/generate-spec";
